### ISSUE TITLE
outdated links in to flyspray

### ISSUE THREAD

**Issue by leamas** [rgleason/ocpn-dev-manual#15]
Several outdated flysparay links, look for willkamp.com

**Comment by rgleason** [comment]
Yes, those are very old and need to be removed.

**Comment by rgleason** [comment]
Fixed the links, then fixed the line endings to LN and found no whitespaces.

Still get this


Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
        modified:   modules/ROOT/pages/prerequisites.adoc
        modified:   modules/ROOT/pages/updating_the_user_manual.adoc

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        .gitignore


Rick@Dart MINGW64 ~/documents/github/ocpn-dev-manual (main)
$ git commit -am "change links to willkamp.com"
modules/ROOT/pages/prerequisites.adoc:124: trailing whitespace.
+Use properly configured Github Pull Requests that build with a green check please

Rick@Dart MINGW64 ~/documents/github/ocpn-dev-manual (main)
$ git status
On branch main
Your branch is up to date with 'origin/main'.

Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
        modified:   modules/ROOT/pages/prerequisites.adoc
        modified:   modules/ROOT/pages/updating_the_user_manual.adoc

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   modules/ROOT/pages/prerequisites.adoc
        modified:   modules/ROOT/pages/updating_the_user_manual.adoc

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        .gitignore


Rick@Dart MINGW64 ~/documents/github/ocpn-dev-manual (main)
$ git add modules/
warning: LF will be replaced by CRLF in modules/ROOT/pages/prerequisites.adoc.
The file will have its original line endings in your working directory
warning: LF will be replaced by CRLF in modules/ROOT/pages/updating_the_user_manual.adoc.
The file will have its original line endings in your working directory

Rick@Dart MINGW64 ~/documents/github/ocpn-dev-manual (main)
$ git commit -am "change willkamp"
modules/ROOT/pages/prerequisites.adoc:124: trailing whitespace.
+Use properly configured Github Pull Requests that build with a green check please

Rick@Dart MINGW64 ~/documents/github/ocpn-dev-manual (main)
$


What exactly does this mean?
+Use properly configured Github Pull Requests that build with a green check please

**Comment by leamas** [comment]
> Untracked files:
(use "git add ..." to include in what will be committed)
.gitignore

Means that .gitignore is yet not in the index (a k a the staging area). Practically  this means that it will no be included when you push things. Fix using `git add .gitignore`, commit and push.

> warning: LF will be replaced by CRLF in modules/ROOT/pages/prerequisites.adoc.

It does the right thing on Windows, which uses CRLF for line endings, when you checkout that file. Still, git thinks windows is weird and displays a warning. https://tanutaran.medium.com/solving-git-lf-will-be-replaced-by-crlf-7ca84eb0aad4

**Comment by leamas** [comment]
Please don't forget to close this bug when you have pushed your changes.

**Comment by rgleason** [comment]
Still get the message


```
Rick@Dart MINGW64 ~/documents/github/ocpn-dev-manual (main)
$ git status
On branch main
Your branch is up to date with 'origin/main'.

Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
        modified:   modules/ROOT/pages/prerequisites.adoc
        modified:   modules/ROOT/pages/updating_the_user_manual.adoc

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        .gitignore


Rick@Dart MINGW64 ~/documents/github/ocpn-dev-manual (main)
$ git add .gitignore

Rick@Dart MINGW64 ~/documents/github/ocpn-dev-manual (main)
$ git commit -am "add .gitignore"
modules/ROOT/pages/prerequisites.adoc:124: trailing whitespace.
+Use properly configured Github Pull Requests that build with a green check please   <--------HERE

Rick@Dart MINGW64 ~/documents/github/ocpn-dev-manual (main)
$ git status
On branch main
Your branch is up to date with 'origin/main'.

Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
        new file:   .gitignore
        modified:   modules/ROOT/pages/prerequisites.adoc
        modified:   modules/ROOT/pages/updating_the_user_manual.adoc

```

**Comment by leamas** [comment]
But isn't the error message pretty clear? That modules/ROOT/pages/prerequisites.adoc has trailing whitespace on line 124? And that you need to fix that before you can commit? 

This is the pre-commit hook in action.

**Comment by rgleason** [comment]
Darn little spaces! 

```
Rick@Dart MINGW64 ~/documents/github/ocpn-dev-manual (main)
$ git commit -am "outdated links"
warning: LF will be replaced by CRLF in modules/ROOT/pages/prerequisites.adoc.
The file will have its original line endings in your working directory
[main 9b0cd50] outdated links
 3 files changed, 6 insertions(+), 10 deletions(-)
 create mode 100644 .gitignore
```

Ok there are changes in the remote. 


```
Rick@Dart MINGW64 ~/documents/github/ocpn-dev-manual (main)
$ git branch -va
* main                9b0cd50 [ahead 1] outdated links
  remotes/origin/main 3ee96e8 Merge pull request #14 from leamas/attachments-7

```
Then?  Push my changes up first, then 

git rebase origin/main?

**Comment by leamas** [comment]
the other way around: first rebase, then push.

**Comment by leamas** [comment]
After a successful rebase you know you can push without problems i. e., without conflicts. That's sort of the very idea, to prepare a push.

**Comment by rgleason** [comment]
Now I think I get it. I had accepted your PR and merged them on the remote  merge number 22 and 28 after merge 14 which my local repository was up to date with  14.   So I have a new commit in my local but there are also your new commits in my remote repos, therefore I have to rebase my change on top of yours before I can push.   git rebase origin/main

```
Rick@Dart MINGW64 ~/documents/github/ocpn-dev-manual (main)
$ git rebase origin/main
Current branch main is up to date.
```
Then

```
Rick@Dart MINGW64 ~/documents/github/ocpn-dev-manual (main)
$ git push origin main
To https://github.com/rgleason/ocpn-dev-manual.git
 ! [rejected]        main -> main (fetch first)
error: failed to push some refs to 'https://github.com/rgleason/ocpn-dev-manual.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

Rick@Dart MINGW64 ~/documents/github/ocpn-dev-manual (main)
$ git pull
remote: Enumerating objects: 71, done.
remote: Counting objects: 100% (71/71), done.
remote: Compressing objects: 100% (28/28), done.
remote: Total 56 (delta 28), reused 48 (delta 22), pack-reused 0
Unpacking objects: 100% (56/56), 730.92 KiB | 858.00 KiB/s, done.
From https://github.com/rgleason/ocpn-dev-manual
   3ee96e8..48dc325  main       -> origin/main
Merge made by the 'recursive' strategy.
 modules/ROOT/attachments/beautify.cfg              |  51 +++
 modules/ROOT/attachments/codestyle.xml             | 167 ++++++++++
 modules/ROOT/attachments/oplaydo1_code.zip         | Bin 0 -> 7797 bytes
 .../attachments/tc47-test-tw-calc-with-stw.pdf     | Bin 0 -> 1496220 bytes
 .../tc53-test-current-spd.dir-w-leeway.pdf         | Bin 0 -> 653118 bytes
 modules/ROOT/images/clone.png                      | Bin 0 -> 69906 bytes
 modules/ROOT/images/vs2013.png                     | Bin 0 -> 13157 bytes
 modules/ROOT/nav.adoc                              |  13 +-
 ...lling_on_cubieboard_2_with_hw_acceleration.adoc |  51 +++
 modules/ROOT/pages/community.adoc                  |  20 +-
 modules/ROOT/pages/fork_build_windows.adoc         |   9 +-
 modules/ROOT/pages/oplaydo1.adoc                   |  15 +-
 modules/ROOT/pages/pi_installer_dev_procedure.adoc |  30 +-
 modules/ROOT/pages/pi_installler_dev_setup.adoc    |   2 +-
 modules/ROOT/pages/plugin_api_versions.adoc        |   7 +-
 modules/ROOT/pages/plugin_documentation.adoc       |  19 +-
 modules/ROOT/pages/plugin_guidelines.adoc          |  11 +-
 modules/ROOT/pages/plugin_languages.adoc           | 368 +++++++++++++++++++++
 modules/ROOT/pages/plugin_page_template.adoc       |  24 ++
 modules/ROOT/pages/plugin_submissions.adoc         |   6 +-
 20 files changed, 722 insertions(+), 71 deletions(-)
 create mode 100644 modules/ROOT/attachments/beautify.cfg
 create mode 100644 modules/ROOT/attachments/codestyle.xml
 create mode 100644 modules/ROOT/attachments/oplaydo1_code.zip
 create mode 100644 modules/ROOT/attachments/tc47-test-tw-calc-with-stw.pdf
 create mode 100644 modules/ROOT/attachments/tc53-test-current-spd.dir-w-leeway.pdf
 create mode 100644 modules/ROOT/images/clone.png
 create mode 100644 modules/ROOT/images/vs2013.png
 create mode 100644 modules/ROOT/pages/building_and_installing_on_cubieboard_2_with_hw_acceleration.adoc
 create mode 100644 modules/ROOT/pages/plugin_languages.adoc
 create mode 100644 modules/ROOT/pages/plugin_page_template.adoc

Then rebase.

Rick@Dart MINGW64 ~/documents/github/ocpn-dev-manual (main)
$ git rebase origin/main
Successfully rebased and updated refs/heads/main.

Then push

Rick@Dart MINGW64 ~/documents/github/ocpn-dev-manual (main)
$ git push origin main
Enumerating objects: 14, done.
Counting objects: 100% (14/14), done.
Delta compression using up to 8 threads
Compressing objects: 100% (6/6), done.
Writing objects: 100% (8/8), 861 bytes | 861.00 KiB/s, done.
Total 8 (delta 4), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (4/4), completed with 4 local objects.
To https://github.com/rgleason/ocpn-dev-manual.git
   48dc325..e45210a  main -> main

```
