### ISSUE TITLE
WD formatting  -what is used for a break in asciidoc?

### ISSUE THREAD

**Issue by rgleason** [rgleason/ocpn-dev-manual#17]
I would like to have images to the left rather than centered. When I format images as a block as follows:

`image::s-wdpi-04b.png[s-wdpi-04b.png,role=left]`

The text all flows up to the right which I don't want.
Do I need a break or page break to keep the block working I think.
I hope a break would be acceptable. That is what we could use in Dokuwiki.   (\\)
What would I use in asciidoc to keep the image as a block across the entire page?

**Comment by leamas** [comment]
No idea, frankly.  But given all the work we need to do I suggest we just leave this for now.
