### ISSUE TITLE
WD formatting - How to create a TOC that expands and contracts?  etc?

### ISSUE THREAD

**Issue by rgleason** [rgleason/ocpn-dev-manual#18]
Also should the TOC be in the upper left corner?
Also I saw an antora TOC that had a hamburger to get it out of the way. Would that be useful?

**Comment by leamas** [comment]
Personally, I find the Antora basic layout with the navigation bar to the left (which we easily can tailor as we like) and the auto-generated contents to the right is at least good enough to not focus on right now.

**Comment by leamas** [comment]
We can do anything we like when we dig into #3, where will customize the default UI (after cloning that site). But this has no priority now, and I would like to close this one.
