### ISSUE TITLE
WD output -  Bdbcat wants to have PDF output. How? Where?

### ISSUE THREAD

**Issue by rgleason** [rgleason/ocpn-dev-manual#19]
For plugin documentation, if we decide to use PDF format with TOC etc.,

How do we get that output built?
Where should it be stored to be included in the tarball?
Should it be in a certain directory?

**Comment by leamas** [comment]
It does seem possible, although still not mature. That said, we need to think about the PDF requirement twice. As I see it, the primary use case is an ordinary end-user in a yacht, where a pdf copy makes some sense. But for the development manual I cannot see that this is important, off-line developing based on pdf  manuals is, well, not that common.

**Comment by leamas** [comment]
Basically, I want to close this one. OK?

**Comment by rgleason** [comment]
Ok, where do we get this discussed and implemented?

**Comment by leamas** [comment]
See https://github.com/OpenCPN/OpenCPN/issues/2071

**Comment by leamas** [comment]
OF course, if we have something like slack/zulip/irc/whatever this would be the place.
