### ISSUE TITLE
WD programming for offline documentation?

### ISSUE THREAD

**Issue by rgleason** [rgleason/ocpn-dev-manual#20]
What do I need to do to WD to have access to the offline PDF documentation?

Will a short section of code solve this?

**Comment by leamas** [comment]
WD ?

**Comment by rgleason** [comment]
WD  WatchDog

**Comment by leamas** [comment]
Ah...sorry. As I see it

  -  we should focus on the Development Manual (DM)  when it come to this attempt to move more modern tools.
  - The plugin manuals, including the WD one, looks like end-user info in my eyes, and should really be part of the User Manual.
  - There is no need for a pdf variant of the DM, the need is for the User Manual (UM)
  - We could postpone the PDF parts until we have a decision on the UM. The idea is that after converting the DM we know more about this and can make a better decision about the UM.

**Comment by rgleason** [comment]
The reason I thought we started doing this was to get the Plugin documentation incorporated in the build process, because you did not like the fact that there was no documentation. This does several things that are good.
1. Plugin documentation goes with the release of the plugin which is easier for the User.
2. I conforms with the way you want thee documentation to work.
3. It simplifies the User Manual and gets rid of internal issues with where screenshots and files are dumped by unknowing editors, etc. so that we can clean up the User Documentation in the Dokuwiki prior to deciding what to do about that.

Because you wanted the documentation included with the plugins I thought that was the main focus to make sure it works right.  Right now I see the User Plugin Documentation as separate from the full User Manual which we can discuss and address after we have a solution for the plugins.

The Dev Manual does need lots of work and editing, but I think that's going to take awhile. I am certainly willing to work on it with others and if it goes well maybe we take a break and then tackle the User Documentation .

**Comment by leamas** [comment]
Yes, things change over time.  I couldn't foresee everything, and sometimes I'm plain wrong.

I have som thoughts on this, but let's wait until we have our channel in place.

**Comment by rgleason** [comment]
Look forward to learning more and discussing there. Closing

**Comment by leamas** [comment]
But you didn't close :) I'll do it.
