### ISSUE TITLE
ODM ocpn-dev-manual   We need a "Edit Docs"  page to enter Dev antora/ascii configure info

### ISSUE THREAD

**Issue by rgleason** [rgleason/ocpn-dev-manual#21]
ocpn-dev-manual  needs an "Edit Docs"

Setup
1. Prerequisites
2. Antora/Ascii software needed with links.
3. Steps to check setup
4. Examples for Editing Plugin Docs
    - Shipdriver  - File structure and antora.yml and site.yml
    - Watchdog  - File structure and antora.yml and build.yml
    - Typical commands and process.
    - How to work locally.
5.  ocpn-dev-manual  Example for editing Dev Manual
    -  File structure and antora.yml and other yml. 
6. Firefox estension  live.asciidocter.js for viewing

**Comment by rgleason** [comment]
Goal is to help Dev Editors get setup and using the system.

Draw info from these threads

https://github.com/Rasbats/shipdriver_pi/issues/159

https://github.com/OpenCPN/OpenCPN/issues/2071#issuecomment-803509220

**Comment by leamas** [comment]
I don't think it's needed. Github has a clever system where after forking a repo user can edit the page directly in the web UI. Also, since this is asciidoc, it's possible to see the results directly (but without navigation etc). Developers knows how git works and will be happy to work this way, besides those who just forks, makes an edit and pushes a PR.

The User Manual is another issue, but this is just not actual for now.

**Comment by leamas** [comment]
Basically, I want to close this one. OK?

**Comment by leamas** [comment]
BTW: There is already hooks for this in the standard layout: https://docs.antora.org/antora/2.2/playbook/configure-edit-url/

**Comment by rgleason** [comment]
You can close it but if my experience is any indicator, there will be people floundering without clearer direction.
For windows there are too many alternative ways to install and some of them do not work, also I still don't have a way to work locally and committing and pushing and then antora fetching is a bit ridiculous.

Also it took me ages to get WatchDog configured so it renders well.
Combine the days getting setup and understanding with the 2.5 days to convert, I don't think you'll see a stampede of conversion when the wiki just works easily.
