### ISSUE TITLE
RFE: Unstructured discussion forum

### ISSUE THREAD

**Issue by leamas** [rgleason/ocpn-dev-manual#23]
The vast amount of bugs in this repo as well as the discussion in https://github.com/OpenCPN/OpenCPN/issues/2071 somehow indicates the need for a discussion forum like a Slack or Irc channel. I have thought about it after one of Mike's questions earlier today.

Working with Antora I stumbled over zulip, which looks like a good alternative to slack (which isn't free). 

But, the basic issue: would you be interested in evaluating for example zulip or Irc as a complimentary tool  besides the Github bugs? A room (or more) where we can just discuss things  which are not (and should not be)  github issues?

@rgleason  @Rasbats: Thoughts?

**Comment by Rasbats** [comment]
> slack (which isn't free).

I have been using Slack for some time for helping a plugin developer. For small teams I think Slack is free.

**Comment by leamas** [comment]
RIght, if you say so (was a long tiume since I checked this, sorry). But the important issue: Interested in using whatever tool we agree on, instead of just using github issues?

**Comment by rgleason** [comment]
I logged into zulip and could use that, but I think I also have an unused slack account.

**Comment by leamas** [comment]
@rgleason : Can I take this as a "yes" to the basic question that you are interested in using a forum like slack or zulip end not just github issues?

**Comment by Rasbats** [comment]
Happy with zulip. @leamas: Are you happy to set this up?

**Comment by rgleason** [comment]
yes, zulip is ok too.

**Comment by leamas** [comment]
I always prefer open-source software when there is a choice. Seems that we all agree on zulip.  

Any volonteer to create our first room/channel/stream, and bring info so we other can subscribe?

**Comment by rgleason** [comment]
Alec or Mike can you do that I barely know slack or zulip

**Comment by leamas** [comment]
MIke: you should have an invitation.
Rick;: I need your email address, don't find it in the logs. Can you send it to leamas dot alec AT gmail?

**Comment by leamas** [comment]
IN case you don't get the zulip invitaion email, here is a link supposed to bring you in: : https://opencpn.zulipchat.com/join/zjcfktb3w55pmo2rvf6vf7n5/

**Comment by leamas** [comment]
I have  dropped an initial message in the opencpn stream  here: https://opencpn.zulipchat.com/#narrow/stream/282854-general

Would be great if you just said 'Hello' or so there.

**Comment by rgleason** [comment]
I have left  several messages here
https://opencpn.zulipchat.com/#narrow/stream/282854-general

**Comment by leamas** [comment]
All  have dropped at least a note on zulip. Let's continue there...

Closing
