### ISSUE TITLE
image files  - problems

### ISSUE THREAD

**Issue by rgleason** [rgleason/ocpn-dev-manual#24]
You say there are now no link failures, checked with link checker.

However just looking at the media files I know there is at least 1..5mb of unused media files.
Also I am certain that there are missing media files for the DEV Manual, so I wonder about the fact that there are no failed links.

Did you remove a bunch of image links?  If so, maybe we should start over?

 Meanwhile should I try to hunt up any of those missing media files.... ?
I have some experience unwiring these deviations in the Dokuwiki.

**Comment by rgleason** [comment]
We need a tool that will list unused (not linked)  media files and images so they can be removed or reused.

**Comment by leamas** [comment]
My thinking is that we in a first step rather mechanically just moves everything from dokuwiki to antora. The next step would be to re-organize and review the docs, but we are still not at a point where we are ready to do that (?).

For now, perhaps the easiest would be to just move everything, postponing the thinking to a later stage even if some of these docs are really old. Since there are no unresolved links in the current antora docs, this means I should add a temporary link in the navigation bar for each new file so we don't lose it.

**Comment by leamas** [comment]
Sorry for unfocused post above, please disregard.

The important thing is IMHO  to compare the dokuwiki site with the antora site side-by-side and check if there is anything missing, complete files or images. If there is unlinked stuff not visible we can surely drop it.

**Comment by leamas** [comment]
When I try to compare current dokuwiki with antora atfer merging #28, I cannot see that anything actually is missing. Got really tired at the end, so anything is possible. But it looks good to me. 

If my conclusion is true, it would mean that we could and should avoiding the rest. Or?

**Comment by rgleason** [comment]
Alec I agree with your thinking get them the same and then remove all old cruft as you put it then edit down and reorganize.
I have gone through the dokuwiki and antora versions side by side once, fairly quickly. That resulted in the list for pages.
I am in the middle of checking the list and separating it into Missing and Found at the bottom.

**Comment by rgleason** [comment]
I think if we do the User Manual I should clean it all up so the media files are properly located and  the pages are all good, Then do do some prelim editing of it to get it more current (not too much).  Then we transfer it if we decide to.  I think that process is more time effective.

**Comment by leamas** [comment]
perhaps. But it's a big *if*.  Need your opinioan on zulip...

**Comment by rgleason** [comment]
zulip  I signed into and left notes
