### ISSUE TITLE
Intent to drop some files

### ISSUE THREAD

**Issue by leamas** [rgleason/ocpn-dev-manual#25]
While comparing the dokuwiki site and current antora docs I see stuff which, at a glance, don't seems to be worth migrating for various reasons:

  - Developer Plugins: this is part of a bigger discussion, currently in zulip, we need a more overall conclusion before trying to handle this.
  - EDITOR MANUAL: this is dokuwiki-specific, does not makes sense on antora.
  - Git Notes, Change Toolbar Button Order, SiteExport Export Failures, SiteExport Plugin Config,
TOC: off-topic in the antora environment (some notes also looks private).

EDIT: 
  - The GNU license, no need to bundle that in the manual, there are official links on fsf.org to tah.

Boat Gallery is already dropped.

OK?

**Comment by rgleason** [comment]
Editor Manual is not going to be migrated. I will make it its own dokuwiki Book  - no
Git Notes (I haven't looked at this at all but I think it would be helpful),   ?
Change Toolbar Button Order,  -  Is this a User thing  ?
SiteExport Export Failures, SiteExport Plugin Config,   -No this belongs with editing.

Developer Plugins -  ???    This section is more than just the Beta Plugins  - we need to discuss this further in Zulik
Note:   We can't just drop the Developer Plugins, they have to go somewhere!  These are Beta Plugins.
They could be left on the Wiki for the time being, but we need a place for them. 
They do not belong in the User Area really as they are buggy at first and not ready,
We don't want all users venturing there, just testers.

**Comment by rgleason** [comment]
Re Git Notes  - Alec this is your domain. It is about process building and compatibilty such that plugins are named appropriately. 
Hopefully we have this under control now and it can be made clearer under the API list.  I would remove this. page.

Change toolbar button order  - This shouldd be put in flyspray. I will do that.  Drop it.

Thanks.

**Comment by rgleason** [comment]
Second thought, that Change toolbar order is for v4.6 an very old. There aren't as many selections anymore, they've moved to the top menu    Wont add to flyspray

**Comment by leamas** [comment]
Seems that we are zooming in. The big thing is how to handle plugin manuals in general, and specifically the beta ones. This is the zulip discussion, and sort of outside the scope of this bug.

As for the Git Notes I actually don't find them that useful.  Let's remember them and migrate if need be.

That said, I think we have agreed to drop the rest of the list I mentioned (?) Time to close?
