### ISSUE TITLE
4. Organization and Missing Files - List of missing files revised.

### ISSUE THREAD

**Issue by rgleason** [rgleason/ocpn-dev-manual#32]
I went through the commits and revised this.
The bottom has the FOUND and ADDED files.

[Missing-Pages-in-Antora-ascii-revised.txt](https://github.com/rgleason/ocpn-dev-manual/files/6182302/Missing-Pages-in-Antora-ascii-revised.txt)

**Comment by leamas** [comment]
>This is the Plugin API link
https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:developer_manual:plugins:plugin_api:plugin_api_versions

This exists just fine as plugin_api_versions.adoc, linked from the naviugation bar.  Anything wrong with that?


>Missing these Compiling pages
https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:developer_manual:developer_guide:compiling_windows:cross_compiling_for_windows_under_linux
https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:developer_manual:developer_guide:compiling_windows:compiling_external_plugins_and_building_install_packages
https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:developer_manual:developer_guide:compiling_windows:compiling_plugins_to_debug
https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:developer_manual:developer_guide:compiling_windows:nsis_installation_directory
https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:developer_manual:developer_guide:compiling_windows:nsis_table
https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:developer_manual:developer_guide:compiling_windows:vs2015_workflow
https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:developer_manual:developer_guide:compiling_windows:compiling_windows_-_steps_-_example
https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:developer_manual:developer_guide:compiling_windows:compile_win_ov4_wx3.0.2
https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:developer_manual:developer_guide:compiling_windows:compiling_windows_mingw
https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:developer_manual:developer_guide:internationalization

Right, I  will look into those.

**Comment by leamas** [comment]
And, again: The Development plugins is a separate issue, we need you on zulip.

**Comment by rgleason** [comment]
Yes, I have some ideas.

**Comment by leamas** [comment]
> https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:developer_manual:developer_guide:internationalization

The corresponding page internationalization.adoc is there, thats all there is to it.

Development Plugins:  Most of the links (all?) besides the plugin manuals lives under Plugin API

Please double-check #25, for example the gplv2 file

That said, here are some missing files. The problem is just that I cannot find a link to them in the menu. Take for example the Beta Plugin page. There is no link to that in the pages we have  migrated. And it's not visible in the current dokuwiki navigation bar. So, how do users find this file today. Google?

**Comment by rgleason** [comment]
Yes dev plugins separate issue.

> This exists just fine as plugin_api_versions.adoc, linked from the navigation bar. Anything wrong with that?


Yes, internationalization  is here and you do have it, but there is a page below Plugin_Languages
https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:developer_manual:developer_guide:internationalization
https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:developer_manual:developer_guide:internationalization:plugin_languages


> Missing these Compiling pages
I assume you are adding these from above?

> Beta Plugin page. There is no link to that in the pages we have migrated. And it's not visible in the current dokuwiki navigation bar. So, how do users find this file today. Google?
I may be called Dev Plugins
https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:developer_manual:plugins
or Plugins Under Development
https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:developer_manual:plugins:beta_plugins
there are some notes there that might be used.

**Comment by leamas** [comment]
> Beta Plugin page. There is no link to that in the pages we have migrated. And it's not visible in the current dokuwiki

Anyway, it's part of #35.

Time to close? Or to narrow down?

**Comment by rgleason** [comment]
Just looking, this looks pretty good for a start.
https://github.com/rgleason/ocpn-dev-manual/blob/main/modules/ROOT/nav.adoc
