### ISSUE TITLE
WD  Watchdog Documentation

### ISSUE THREAD

**Issue by rgleason** [rgleason/ocpn-dev-manual#36]
I finished this finally. Learned how to work locally with build-loc.yml
Then added and pushed to remote repos.  
Cleaned up excess images using linkchecker
Then used linkchecker and file directory to remove unused images to old directory.
Then did linkchecker.

Found here 
https://github.com/rgleason/watchdog_pi/tree/master/modules/ROOT

**Comment by rgleason** [comment]
Alec, 
I want to squash all the damn commits I had to make for documentation, in the master branch.
This changes history, but I don't think anyone has updated their repos lately.
What should I do?

**Comment by rgleason** [comment]
Also should I move  modules into a new "manual" directory and change the build.yml and build-loc..yml files and move them down too?   Or just leave it as is?

**Comment by leamas** [comment]
Time to move to the plugin repo?

**Comment by rgleason** [comment]
First question -  Should I squash?  I don't think anyone forked this stuff.

```
Alec,
I want to squash all the damn commits I had to make for documentation, in the master branch.
This changes history, but I don't think anyone has updated their repos lately.
What should I do?


```https://github.com/rgleason/watchdog_pi/commits/master

**Comment by leamas** [comment]
There are multiple ways to to this. I tend to use interactive rebase (rebase -i) which has a learnign curve but is really powerful. You will need to google this, it requires a primer.

If you havn't, using git commit --amend is the way to avoid this situation next time.

**Comment by rgleason** [comment]
I'll use interactive rebase, I've done that a number of times.  Thanks.
Did not know about git commit --amend.  very useful

**Comment by leamas** [comment]
> Also should I move modules into a new "manual" directory and change the build.yml and build-loc..yml files 

IMHO, it's no point, I don't see the valuet. But eventually,it's your decision.

**Comment by rgleason** [comment]
Thanks, I am just going to leave it.  git rebase -i HEAD~10 worked well for me, I had about 30 commits to do.
Going to close this Thanks.

**Comment by leamas** [comment]
OK. We need you on zulip...
