### ISSUE TITLE
Images - Questions Suggestions

### ISSUE THREAD

**Issue by rgleason** [rgleason/ocpn-dev-manual#37]
Alex,

There are a bunch of watchdog images in there that are not needed there.  about 1.5 mb I think I can give more detail.
but the WD images are listed here https://github.com/rgleason/watchdog_pi/tree/master/modules/ROOT/images
old images in the old directory in case needed.

To give you some ideas of what they look like. 

Question
do you want some icons for the various OS?  
Windows
Linux
Mac
Rpi?

**Comment by leamas** [comment]
Let's leave this for now. Will file new bug on the organization of data, and after  that we will come to places where these can be needed.
