### ISSUE TITLE
New manual structure.

### ISSUE THREAD

**Issue by leamas** [rgleason/ocpn-dev-manual#38]
For now, the structure i. e., the left-pane navigation bar is extremely disorganized and hard to find stuff in. I suggest that we start from the beginning and designs a new structure.

An initial shot in the dark:

```
- Intro (history etc)
- About this manual (scope, what's in the different parts)
+ Opencpn  development
+ Plugin Development
+ Plugin Installer and CI
+ Manual maintenance
+ Attic
```

That is, the initial navigation bar is just these 7 lines.

Attic is the place where we place stuff which is unmaintained, we don't really know if it's useful, but we still hesitate to throw it away. Just like old stuff in the house we don't use but don't want to throw away which finds it's way to the attic. 

@rasbats @rgleason : thoughts?

**Comment by Rasbats** [comment]
I think it would be good to mock things up with the general outline, with minimal content. 
Review to see how it works. 
Then add more content etc. 
Baby steps.

**Comment by leamas** [comment]
Yes... 

Or: another approach: We sort everything we have under the outline. And then starts which each heading: Review, update, move to attic, write new text.

The middle-way: We start by fixing intro and "About". Next step: move everything we have on opencpn development under that header, and starts the review/update/move-to-attic/write process there. The balance between baby steps  and re-using the stuff we actually have.

**Comment by Rasbats** [comment]
This has been useful:
[https://pagure.io/fedora-docs/install-guide/tree/master](https://pagure.io/fedora-docs/install-guide/tree/master)
Produces a good structure.

**Comment by leamas** [comment]
yes... eventually, we will have to clone a UI bundle (for example  the default or the one in link above), and make our own changes. This is #9

**Comment by Rasbats** [comment]
Dropped a prototype in here:
[https://github.com/Rasbats/ocpn-user-plugins-manual](https://github.com/Rasbats/ocpn-user-plugins-manual)

**Comment by leamas** [comment]
Right. 

You should be able to refer to the local bundle directly, without going the rather awkward http roundtrip.

Is is published anywhere, so we can see the results?

**Comment by rgleason** [comment]
I would like to see "Plugin Manager" -your version and "Plugin Package Installer"
but I am not quite sure what is in each section..  I may have missunderstood.

- Intro (history etc)
- About this manual (scope, what's in the different parts)
+ Opencpn  Development
+ Plugin Development
+ Plugin Manager and CI    (For Devs - new way build, deploy tarballs, integrate)
+ Plugin Package Installer (?)   (For Devs-  old way build and distribute packkages)
+ Manual maintenance  (How to setup and use antora?  How to make changes and update pages outflow)
+ Attic  - (old pages and images?

I agree about mockup, maybe with a rough outline
I like the Fedora link and the way it works.  (The text has to be made short and concise!)
The list above is too long.  Below is just a another shot

Title - OpenCPN Developer Manual
+ Intro
+ About
+Manual
+PI Manual
+PI Manager
+PI Package
+CI
+Maintain
+Attic

BTW
This is a keyboard full to type  "ocpn-user-plugins-manual"  and I don't look forward to doing that all the time.

**Comment by leamas** [comment]
Plugin Package can (should?) be contained with Plugin Development. This is nowadays basically a legacy.

The reason to lift the PI manager  to the top level is that it is an integration and sits in between main opencpn and the plugins; this is not obvious for the traditional packages.

Any attempt to divide PI manager and the CI setup is IMHO likely to fail, they are tightly integrated. Another aspect is that we have two big pieces, the testplugin and the shipdriver workflow. Both covers both plugin development  and CI setup, and to split each of them to two pieces will not be nice. Ergo: keep PI installer and CI in one piece.

**Comment by rgleason** [comment]
Ok, Like this?

    Intro
    About
    +Manual
    +PI Manual
       + Compiling
       + API
       +PI Package 
       + etc  
   +PI Manager+CI
       +Cloud Accounts & Services
       + Process Diagram
       + ShipDriver frontend1
       +Testplugin frontend2
       + Opencpn/Plugins Process
       + Other important stuff 
    +Maintain
    +Attic

**Comment by leamas** [comment]
No. What is "Manual" supposed to mean in this context? And what is the meaning of "PI"?

We have opportunities to introduce all sorts of acronyms in the text. But a reader facing the overview for the first time will not know them, and needs the simple names: opencpn for main program, plugins for plugins.  We might need to use CI, but that's a fairly accepted abbreviation.

Also, I'm not really prepared to discuss the inner life of each heading at this point.  What you propose basically looks fine, but it's just too early. 

Removing the inner life, you propose:

```
- Intro
- About
- Manual
- PI Manual
- PI  Manager - CI
- Maintain 
- Attic

```
My proposal is:

```
- Intro 
- About this manual
+ Opencpn  development
+ Plugin Development
+ Plugin Installer and CI
+ Manual maintenance
+ Attic
```

What is you thinking about the revised heading names?

**Comment by leamas** [comment]
Thinking about  _Plugin Installer and CI_. The keywords to use should really be 'deploy' and 'CI', but my pidgin Englisch tends to morph it into 'deployment' and 'CI' which leads to a long, perhaps too long header.

A header containing *deploy*, *plugins* and *CI* in a sane, short phrase would be nice. Deployment of course also covers the legacy packaging.

**Comment by jongough** [comment]
Just a thought, with the new build process, i.e. circleci, appveyor and docker, it may be worth including a section on local builds using these environments. I now use circleci local for builds that rely on docker images at the high level and docker using the ci/*.sh scripts for those that have machine true at the high level as they will run on Ubuntu 16.*/18.*. For appveyor I use 'git bash' on windows and then run the contents of the scripts against VS17. This does avoid too many commit/push cycles but does really rely on local git commits and using local git pull's.

This process also allows local testing by using the 'import' button for the generated packages AND you can run debuggers to step through the code if needed. Android is more difficult to test, although I am looking at Android Studio and using its virtual android devices to help cover this space.

**Comment by leamas** [comment]
Hi Jon.

This is about the plugins, and we are far from there yet (currently trying to write an introduction, and immediately runs into troubles)

That said, we should certainly have info on this, it's an important and somewhat overlooked topic. 

One thought which has crossed my mind is based in the new manual structure. I don't know how much you have picked up, but the basic setup that the manual consists ot several "sub-manuals" i. e., Antora components which are maintained separately. The overall manual basically merges the different component to a common manual.  My idea is that we should break out the frontend2 stuff to a separate component, which you could maintain. 

Thoughts?

**Comment by leamas** [comment]
@rgleason  @Rasbats  @jongough   Having some trouble  with the first paragraph. Please chime in on zulip so we not spam this bug.

@jongough : Here is the invitation link: https://opencpn.zulipchat.com/join/yohsxrsydq46olbkyzn6gwjl/

**Comment by rgleason** [comment]
I like "Deploy plugins and CI"
There is going to be a Title for sure... something like
Title - OpenCPN Developer Manual
so we know it is a "manual" and we know it is for "OpenCPN"
so we don't need to repeat those words.
Counter proposal

```
Title - OpenCPN Developer Manual
- Intro
- About
- Opencpn
- Plugin
- Deploy plugins   (CI is part and under that)
- Maintenance 
- Attic
```

**Comment by rgleason** [comment]
Jon wrote:
> including a section on local builds using these environments. I now use...

I'd be lost without being able to build locally, due to my level of skill, and I think such a section or component would be hugely helpful.

I have found using bash locally as you have shown and setup is essential. Not all starting plugin devs will know about or have this knowledge, and helping them out getting setup is really the first step for the plugin part of the manual.

**Comment by leamas** [comment]
@rgleason: zulip, please

**Comment by leamas** [comment]
For now,   code rules. Closing
