### ISSUE TITLE
Windows Compile pages - Missing?  Images?

### ISSUE THREAD

**Issue by rgleason** [rgleason/ocpn-dev-manual#39]
These are some pages you mentioned earlier Alec, that Mike made.

https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:developer_manual:developer_guide:compiling_windows:vs2015_workflow

https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:developer_manual:developer_guide:compiling_windows:compiling_windows_-_steps_-_example

https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:developer_manual:developer_guide:compiling_windows:compile_win_ov4_wx3.0.2

https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:developer_manual:developer_guide:compiling_windows:compiling_windows_mingw

Don't know if you have these or not.  Some of them are a bit of history, but there is good work in here and it might be useful.
How to compile for 4.8.0  etc.   Visual Studio 2013, etc.   
We aren't using some of these pages now, are they worthwhile having or not?
Can they be used as a template for updating documentation, yes I think so, at least one of them.

**Comment by leamas** [comment]
Not the third, but the others. 

Documents which are historic probably will end up in the Attic.

**Comment by leamas** [comment]
BTW: It's not that hard to check. The migrated pages lives in modules/ROOT/pages, basically with the same name as the original but with a .adoc extension

**Comment by leamas** [comment]
Have you found what you need here? Or is there anything more to migrate?
