### ISSUE TITLE
There are no issues...

### ISSUE THREAD

**Issue by leamas** [rgleason/ocpn-dev-manual#4]
... and we need to file them. To be specific: Could you please start the process to check what's missing in current state. If you file the bugs I'll try to fix them.

Better with many small focused bugs than just a few covering too much.

**Comment by rgleason** [comment]
Ok

**Comment by rgleason** [comment]
Don't know the status of the following but,  Missing 
https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:developer_manual:developer_guide:compiling_linux:building_and_installing_on_cubieboard_2_with_hw_acceleration

Remove the indexmenu_n>_   line which ordered the pages in a specific order.  What is doing this now?

Plugin API   link missing    see file:///C:/Users/Rick/Documents/GitHub/ocpn-manuals/docs/ocpn-dev-manual/5.3.1/compiling_windows.html#plugin_api_versions.adoc

This is the Plugin API link
https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:developer_manual:plugins:plugin_api:plugin_api_versions

Missing this
https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:developer_manual:developer_guide:compiling_windows:cross_compiling_for_windows_under_linux

https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:developer_manual:developer_guide:compiling_windows:compiling_external_plugins_and_building_install_packages

https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:developer_manual:developer_guide:compiling_windows:compiling_plugins_to_debug

https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:developer_manual:developer_guide:compiling_windows:nsis_installation_directory

https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:developer_manual:developer_guide:compiling_windows:nsis_table

https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:developer_manual:developer_guide:compiling_windows:vs2015_workflow

https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:developer_manual:developer_guide:compiling_windows:compiling_windows_-_steps_-_example

https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:developer_manual:developer_guide:compiling_windows:compile_win_ov4_wx3.0.2

https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:developer_manual:developer_guide:compiling_windows:compiling_windows_mingw

https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:developer_manual:developer_guide:internationalization
UNderneath missing   https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:developer_manual:developer_guide:internationalization:plugin_languages

**Comment by leamas** [comment]
OK, but could you please file new issues instead? so we can process them one by one (and close this, because at that point we will definitely have issues...)

And, please: rather small, well-defined issues then a single one containing all of above.

**Comment by rgleason** [comment]
Missing Development Plugins  and  everything underneath
Should this be named something else?  Plugin Development  or  Beta Plugins? 
https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:developer_manual:plugins

Sub pages
https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:developer_manual:plugins:plugin_api

     Sub Pages
     https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:developer_manual:plugins:plugin_api:plugin_api_versions
     https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:developer_manual:plugins:plugin_api:ocpn_draw_odapi
     https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:developer_manual:plugins:plugin_api:standalone_plugin_compilation
    https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:developer_manual:plugins:plugin_api:troubleshooting_plugins
    https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:developer_manual:plugins:plugin_api:gpl_v2
 
Sub Pages
https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:developer_manual:plugins:beta_plugins
     Sub Pages     
      https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:developer_manual:plugins:beta_plugins:plugin_page_template
      https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:developer_manual:plugins:beta_plugins:trackpoint
      Plus about 16 other plugins.

**Comment by leamas** [comment]
Again: separate issues, please!

**Comment by rgleason** [comment]
One Line = One Page?

**Comment by rgleason** [comment]
Ok I will redo it and delete.

**Comment by leamas** [comment]
or just a few, if you think they are related and not too complicated ... We need to be able to track things, this will take time.

**Comment by rgleason** [comment]
Remove the indexmenu_n>_ line which ordered the pages in a specific order. What is doing this now?

Plugin API link missing see file:///C:/Users/Rick/Documents/GitHub/ocpn-manuals/docs/ocpn-dev-manual/5.

**Comment by rgleason** [comment]
Ok will do.

**Comment by rgleason** [comment]
Plugin API link missing see file:///C:/Users/Rick/Documents/GitHub/ocpn-manuals/docs/ocpn-dev-manual/5.3.1/compiling_windows.html#plugin_api_versions.adoc

This is the Plugin API link
https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:developer_manual:plugins:plugin_api:plugin_api_versions

**Comment by rgleason** [comment]
Missing these Compiling pages
https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:developer_manual:developer_guide:compiling_windows:cross_compiling_for_windows_under_linux

**Comment by rgleason** [comment]
https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:developer_manual:developer_guide:compiling_windows:compiling_external_plugins_and_building_install_packages

**Comment by leamas** [comment]
> Remove the indexmenu_n>_ line which ordered the pages in a specific order. What is doing this now?

It's anothe concept. The navigation bar is hand-written, so to speak, rather than generated from the pages. And this is actually not hard due to the extremely versatile xref macro. Check he file nav.adoc, this is the source for the navigation bar.

**Comment by rgleason** [comment]
https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:developer_manual:developer_guide:compiling_windows:nsis_table

**Comment by rgleason** [comment]
https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:developer_manual:developer_guide:compiling_windows:compiling_plugins_to_debug

**Comment by leamas** [comment]
Waiting for new bugs I can handle. To be frank: I cannot cope with all the things you have dumped here in this bug, it's too much. Sorry

**Comment by rgleason** [comment]
https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:developer_manual:developer_guide:compiling_windows:compiling_plugins_to_debug

**Comment by leamas** [comment]
Do you listen?

**Comment by rgleason** [comment]
Ok, they are missing pages. I will just list them for now and well have to get them fixed at some point.

**Comment by rgleason** [comment]
I am just comparing the two...

**Comment by leamas** [comment]
If you just could organize it to some reasonable issues I can fix it. Isn't this a reasonable deal?

**Comment by rgleason** [comment]
Sure. Maybe I should make a separate document with missing pages?

**Comment by leamas** [comment]
NO!!!!  Smaller issues we can process and close when they are fixed. A document is back on square one, everything in one place.

**Comment by rgleason** [comment]
I'll deal with the missing pages at some point. I am keeping a list in a document. Still working on it.
As I go through fairly quickly, I'll probably find things that are not missing pages. Maybe miissing links or files.

**Comment by leamas** [comment]
Looking forward to new issues, closing this. Good night.
