### ISSUE TITLE
Prerequisites remarks.

### ISSUE THREAD

**Issue by leamas** [rgleason/ocpn-dev-manual#51]
The title is *Plugin Manager (PM) Prerequisites* 

This is IMHO plain wrong. The PM is the parts of core OpenCPN which handles the plugins. These parts  only requirement is a catalog, and that resources listed in the catalog can be accessed. In particular, PM has no knowledge or requirements on Cloudsmith, this is just an implementation detail which could be changed at any point.

The proper title is IMHO "Workflow Prerequisites" or something like that.

The text mentions bash as a requirement for local builds. This is not true for shipdriver, and should thus be dropped here.

The text also mentions that it should be possible to install the plugin as a legacy package. At least for shipdrvier, this is not required and this should thius also be dropped.

Over

**Comment by rgleason** [comment]
I agree. and will rename  Workflow prereq

**Comment by leamas** [comment]
There are more prerequisite differences between shipdriver and testplugin: shipdriver requires python, always (+ possible more now or later, havn't  reviewed in detail).

The reasonable fix is IMHO to move this page to the testplugin section, where it applies as-is.

**Comment by rgleason** [comment]
Actually Testplugin requires it too.  I think the page should stay where it is.

**Comment by leamas** [comment]
Not really, IMHO. It's not only about the current state, it's also about maintenance. The shipdriver  docs are separate, and chances are  high the this document will diverge from shipdriver over time as shipdriver evolves.  Same is actually true for testplugin if/when someone else gets involved in those docs.

Already now it's messy. The only way to get it right is clumsy sentences like "Both workflows requires python, testplugin also requires bash." This is hard to read and hard to maintain. 

OTOH, devs will know from the beginning if they are using testplugin or shipdriver because they have to. And will be perfectly fine to dispatch to the proper section to find the prerequisites. 

This is logical and simple. What are the arguments against it?

**Comment by rgleason** [comment]
Well, it is pretty clear that if a dev chooses shipdriver he goes to a whole separate workflow and and had gone down a hole and it is kind of hard to get back the way the docs are working now.  So your shipdriver devs are protected.

**Comment by rgleason** [comment]
I also gather that you don't really care too much about testplugin.

**Comment by leamas** [comment]
It's not that I don't  care for this or that. It's about having things in the right place. For me, documentation is a lot like code, and the process right now is the classic refactoring where pieces are moved around in an attempt top get the interfaces right.

I *do* think that the right interface is that the overall parts are more or less agnostic to testplugin and shipdriver internals, and that  specific parts like pre-requisites and workflows are described in the different worfkflow header. This make the overall docs easier to read, since it by definition becomes more high-level. It also makes for example testplugin specifics easier to read, since everything is in one place.

And, not least: it makes things easier to maintain. Chances are big  that docs will be written by authors like me (knows to little about testplugin) or you (knows to little about   shirpdriver). The way to cope with this is that we write the parts we know, and avoids creating complicated situations where for example I should maintain text which is related to testplugin details.

Or, the other way around...

**Comment by jongough** [comment]
> testplugin also requires bash.

This is not really true. Testplugin uses the current cloud 'build' environments and makes them usable locally. So, under windows, git-bash is used as this is what runs the commands in the cloud. For local development only there is no requirement for python or bash just whatever IDE or command line the user prefers. When it comes to testing it is much easier to use the 'cloud' build process locally to build the plugin such that the build process can be checked and you know what you are testing is the same as what will happen for the cloud. 

With the move to use libs and support android this has proved very useful. Testplugin can now be generated locally for all 15 environments and deployed to cloudsmith. However, this does require docker and some virtual machines so that some of the circleci builds can be run (the ones that use a 'special' machine environment, i.e. raspberry pi builds). I have tested testplugin building and running locally using virtual machines on Linux, Windows, MacOS and Android.

**Comment by rgleason** [comment]
bash is used by windows to run the scripts.

**Comment by leamas** [comment]
@jongough: thanks for chiming in.

Still, long story short: This is the situation for testplugin. It's a good explanation'and  parts of it should IMHO be included in the documentation. My only concern is that this is best done in the under the testplugin heading, where it applies fully. Shipdriver is of course similar, but still not the same.

So: nice explanation, appreciated. I suggest that it's worked into the text currently under "Workflow Prerequisites" after moving it to the Testplugin section.

**Comment by leamas** [comment]
The plugin stuff is now re-organized under two headings "Plugin Manager Development " and "Plugin Manager Workflow". IMHO, this does not really makes things better:

- Using the term "Plugin Manager" here is still wrong. *Plugin Manager Development* should refer to development of the Plugin Manager which is part of OpenCPN which clearly is wrong. Likewise for Plugin Manager Workflow.
- Moving the deployment overview under the second heading doesn't seem logical, this is indeed an overview and should come early.
- The stuff under "Workflow Requisites", "Prerequisite Services" and "Cloudsmith Setup" more or less doesn't apply to the shipdriver workflow. Hence, they belong under "Tesplugin Template".
- The remaining part, the "Workflow Overview" is the last item (!).

I suggest that everytihing is sorted under a single top heading "Plugin Development". I'll try to make a PR just to give it some concrete form.

**Comment by leamas** [comment]
Things have improved a lot in   last commit ef08f1525. The overall structure is as I see it fine, with a single Plugin Development header.

However, it's  IMHO still not consistent. The Plugin Development now looks like:

  - Plugin  Guidelines
  - Plugin ABI and API
  - Deployment Overview
  - Prerequisites overview
  - Prerequisites services
  - Workflow Overview
  - Legacy Package Deployment

Here, the *Prerequisites overview*  and *Prerequisites services* are IMHO out of context.

First, the Deployment Overview explicitly states that there are no dependencies on for example Circleci, Cloudsmith or Github for storing sources. That in in next chapter state that they are prerequisites makes no sense. The plugin deployment does *not* requires any service at all besides the github catalog project. If the are requisites, it is for the workflows; either all of them so just one.  Ergo: these two chapters belongs under Workflows.

Second: These two chapters does still not apply to the shipdriver workflow, there are subtle differences. Differences which might grow over time, and all of a sudden we have yet another workflow, who knows? With unknown requisites. Ergo: these two chapters belong under the Testplugin Template heading.

Now. it seems that you don't want them there. And I don't want them anywhere else. Shall we just drop them?

**Comment by leamas** [comment]
Oops... sorry. The whole post above is based on bad assumptions, I built from the wrong commit. Please disregard

**Comment by leamas** [comment]
Please leave a note when you feel ready for feedback!

**Comment by leamas** [comment]
Basically fixed in 12f0c01. Let's move on. Closing
