### ISSUE TITLE
Legacy Plugin Packaging -- out of context

### ISSUE THREAD

**Issue by leamas** [rgleason/ocpn-dev-manual#54]
Some thoughts on the current pages under Legacy Plugin Packaging.
- The page *Plugin Build Files* is not related to legacy packaging in any way, it applies to modern plugins also. Perhaps it could be sorted under Resources?
- The "Plugin Compilation Win" is definitely not applicable to the shipdriver workflow, where a NSIS package is created by `make pkg`. IMHO this means that this file is either applicable to testplugin plugins only in which case it should be sorted under the testplugin heading. Or not at all, in which case it should be dropped.
- Page *Compile Plugins and build Install Packages*: likewise, it does not apply to shipdriver plugins and should IMHO be moved to the testplugin header or dropped.
- Page *Compile Plugins for Debugging*: same, does not apply to shipdriver plugins and should IMHO be moved to the testplugin header or dropped.
- Page "Compile with MinGW".  This should be dropped. Both template sets contains updated build scripts which builds mingw plugins. These are correct (after all, the do build) while the info in this document is severely outdated. Furthermore, the document is about building OpenCPN, not plugins. Building opencpn under mingw is already documented.

**Comment by leamas** [comment]
I made two PR for the first and  last bullet -- they seem to pretty clear-cut in my eyes. However, we need to discuss the rest first, and will not make any more PR until we have.

**Comment by leamas** [comment]
OK, this is great. The open issue(s) is now bullets 2. 3 and 4. What's you thinking on these?

**Comment by rgleason** [comment]
2,3,4 done
