### ISSUE TITLE
developer_guide.adoc: Duplicate.

### ISSUE THREAD

**Issue by leamas** [rgleason/ocpn-dev-manual#55]
The info in developer_guide.adoc overlaps the info in AboutThisManual in a broad sense.

Contrary to AboutThis manual, it also somehow duplicates the info in the navbar, creating maintenance problems.

It also links to the completely out of scope prerequisites.adoc. This is in the attic, so no need to fix it. But we should certainly not link to it. (any link to the attic from non-attic pages is an error which needs to be fixed by removing the link or moving the linked page away from the attic).

In the end, we should IMHO choose between AboutThisManual and developer_guide. I'm obviously biased since I wrote it, but I do think AboutThisManual is an better option.

Thoughts?

**Comment by rgleason** [comment]
I agree. I will remove it. 
My version seems to open on this page because of the setup and there is a redirect to this page.
I will change that too.

**Comment by rgleason** [comment]
Fixed redirect and  moved this to attic redundant
