### ISSUE TITLE
html Start Page  -Dev Guide redirect???? 

### ISSUE THREAD

**Issue by rgleason** [rgleason/ocpn-dev-manual#58]
12:29 PM

We need to get the first page working properly.
The first page to be opened is supposed to be intro-AboutThisManual.adoc or intro-AboutThisManual.html

There is a redirect happening somewhere that I have not been able to determine the source, I've looked in the antora.yml and in other yml and I don't know where it comes from, but the top index.page in ocpn-manuals (where the pages are generated from) in C:\Users\Rick\Documents\GitHub\ocpn-manuals\docs\index.html

Has this redirect which is not correct and refers to developer-guide!

<!DOCTYPE html>
<meta charset="utf-8">
<link rel="canonical" href="https://leamas.github.io/ocpn-manuals/ocpn-dev-manual/5.3.1/developer_guide.html">
<script>location="ocpn-dev-manual/5.3.1/developer_guide.html"</script>
<meta http-equiv="refresh" content="0; url=ocpn-dev-manual/5.3.1/developer_guide.html">
<meta name="robots" content="noindex">
<title>Redirect Notice</title>
<h1>Redirect Notice</h1>
<p>The page you requested has been relocated to <a href="ocpn-dev-manual/5.3.1/developer_guide.html">https://leamas.github.io/ocpn-manuals/ocpn-dev-manual/5.3.1/developer_guide.html</a>.</p>

Where do I fix this? Any ideas?

**Comment by leamas** [comment]
As noted in zulip: is this about documents generated by your local buildxxx.yml or as generated by ocpn-manuals?

I have updated ocpn-manuals:build.yml to handle the renamed startpage intro-AboutThisManual, a new version of the manual is available at https://leamas.github.io/ocpn-manuals/ where all is fine.

Ergo: the problem is about your build.yml. It's the start_page there which goes into index.html

**Comment by rgleason** [comment]
Yes, sir indeed.

site:
  title: OpenCPN Developer Manual
  # the 404 page and sitemap files only get generated when the url property is seto
  url: https://leamas.github.io/ocpn-manuals/
  start_page: ocpn-dev-manual:ROOT:developer_guide.adoc

**Comment by rgleason** [comment]
It is now

 start_page: ocpn-dev-manual:ROOT:intro-AboutThisManual.adoc

you might want to change to that because I renamed the file to collect it with other intro files.

Thanks

**Comment by leamas** [comment]
Already fixed...
