### ISSUE TITLE
Linux  - Tides and GSHHS

### ISSUE THREAD

**Issue by rgleason** [rgleason/ocpn-dev-manual#61]
https://github.com/OpenCPN/OpenCPN/issues/1685#issuecomment-827609770
Linux - Alternative Tide and GSHHS

Against compile on Linux
https://rgleason.github.io/ocpn-manuals/ocpn-dev-manual/5.3.1/od-compile-linux.html

**Comment by leamas** [comment]
Why do you copy text from the link? This IMHO is a bad habit, duplicate stuff which is in the way.  The link is enough, perhaps with a *summary* text. Please try to be concise.

**Comment by rgleason** [comment]
Alec, then the editor has to search through and read everything.

**Comment by leamas** [comment]
Yes, if you paste everything as you do. But if you just use the link, the reader can either follow the link of she wants, or skip it and keep the overview. A far better option, and the one normally used.

Writing a manual is a different thing, there is other logic there. But not in a issue. Be concise, on spot and remove anything not necessary.  Remember the Community Guidelines you referred to. Forcing large chunks of text on the reader is just not good manners.

**Comment by rgleason** [comment]
Updated - All to save 4 lines of text
Why do you chase me around?
