### ISSUE TITLE
AsciiDoc/Antora is a very poor subsitute for Dokuwiki

### ISSUE THREAD

**Issue by rgleason** [rgleason/ocpn-dev-manual#78]
1. AsciiDoc/Antora is arcane and will be difficult for others to pick up and learn (including users who are willing to help with documentation).
2. This difficulty will damage the documentation of plugins.
3. We have yet to see any of the possible advantages of using this system.
4. It would be appropriate to reconsider whether we should continue with this project IMHO, or modify or change direction in some way.

**Comment by leamas** [comment]
Whether AsciiDoc/Antora is arcane or not is basically a subjective opinion. That said, if this opinion was shared among many projects there would be examples of projects moving from Antora-like solutions to wiki-based like Dokuwiki.  I find no such examples out there, but plenty of projects moving from systems like Dokuwiki to Antora. Also, Antora definitely is a newer system and in this sense more "modern" than Dokuwiki. Altogether, I think it's fair to say that labeling Antora as "arcane" can be  and is disputed.

I don't share your opinion that developers (our target users) will find Antora hard to pick up. On the contrary, using ascii-based documentation is a major ttrend in modern projects, and so is of course the git-based workflow. That said, we need better examples and a much more templates before prime time.

 > We have yet to see any of the possible advantages of using this system

Well, I do,  as well as many others including  @Rasbats and @nohal (?)

But the basic message is something else. This is still a work in progress,  and not ready for production. Another aspect is that if you are still not is convinced about the benefits it might be  better to make the continued work in a github repo not owned by you.

For now, the focus is to get 5.6.0 out of the doors. At least for me, this means that the documentation regrettably is not the highest priority.

**Comment by rgleason** [comment]
1. The target user is not Developers, over 50% of the plugin manuals have been created and maintained by users.
2. To users this system is Cumbersome and Arcane, no doubt about it.
3. I did not say that "developers will find it hard to pick up"  - You are obscuring my point.
4. That it is a work in progress is not disputed. The structural deficiencies of antora will remain. It is a cumbersome system.

**Comment by leamas** [comment]
First question: are you  talking about the plugin(s) manual(s), or the development manual?

**Comment by leamas** [comment]
The statement "Antora is arcane" is disputed at least by me, making it disputed. Personally, I find the Dokuwiki system arcane, but that's just a personal, subjective opinion without any data besides that I find projects moving from Dokuwiki to Antora but no  examples of the opposite.

**Comment by rgleason** [comment]
By finalizing this move to asciidoc/antora for Plugins we will  inevitably lose all Editing Volunteer Users for Plugin Documentation.
Do plugin programmers have extra time they are willing to donate for editing their documentation?
I see no one else ready or interested enough to do this task because of the hurdles placed by learning git and asciidoc/antora,

On the positive side, that will leave more volunteers to renew the User Manual and it will clean up the Wiki significantly.

**Comment by leamas** [comment]
First and foremost: This bug is filed against the Developer Manual, but it seems to be about the plugin(s) manual(s).

Here are also all sorts of claims without any actual arguments. 

Personally, I do think the person developing a plugin is and will be the main  contributor to the documentation.  For that reason, keeping the plugin manual as part of the plugin sources  is a major advantage.

There will be no need to learn more than very basic things if/when there are good examples and a descent workflow. However, we are not there yet.

There are simple, GUI tools to make minor updates by  occasional drive-by users. They are at least as simple as Dokuwiki. They require a  github account, but this is most likely less of a barrier than getting a Dokuwiki one.

**Comment by leamas** [comment]
But I the end: If some devs wants to explore the Antora track for plugin documentation, why not let them do this. And evaluate the results if/when there is something to evaluate.

That  said, your statement "Antora is arcane" IMHO needs some citation. It certainly has drawbacks, but arcane? I cannot see thi as a common  opinion out there.

**Comment by rgleason** [comment]
Alec,  I see this as a blanket decision to go with asciidoc/antora or not, which involves all plugins, otherwise it will be a huge mess in two places.  I actually don't think this is something that plugin devs should be deciding since Mike has done all the work to get them moved.

I certainly have a difficult enough time getting users of Dokuwiki to put their screenshots in the right places, let alone figure out which plugin is on dokuwiki and which one is on asciidoc!  Others will be equally confused. Despite my concerns about asciidoc/antora, I think the decision should be a wholesale one.

This raises the issue of timing and the need to edit plugins.  Under Plugins in Dokuwiki User Manual, the Plugins are FROZEN,  there should no further editing there.  All edits of Plugins should be done using asciidoc/antora.

If we are going to change our mind about this, now is the time. Otherwise, lets move forward with this grand experiment and I promise not look back again. -- I think it should be all or nothing.  (We move all the plugins or none.) If you and Mike are in agreement, I will leave those notes as they are.

Also I intend to start deleting the Plugin Documentation from Dokuwiki soon,  as it should not be in two places, and it will clean up and simplify the User Manual considerably and allow that makeover to proceed hopefully this fall.

**Comment by rgleason** [comment]
FYI In the outline the Plugin Manual seems to be under the Dev Manual and it should be moved up (Mentioned earlier)
Github accounts are a hurdle for many users.

**Comment by rgleason** [comment]
For an arcane chuckle [Zachariah Synarri  from The rise of Antora](https://theriseofantora.obsidianportal.com/characters/zachariah-synarri) 

arcane - understood by few; mysterious or secret.
I think that is an apt word to use for Antori (my own personal opinion)

**Comment by Rasbats** [comment]
> I intend to start deleting the Plugin Documentation from Dokuwiki soon, as it should not be in two places

@bdbcat : Still totally unhappy with the idea of using my GitHub account (rasbats.github.io) as a webserver for OpenCPN users. We could use OpenCPN/manuals (opencpn.github.io) if that was set up, but again GitHub might object to that body acting as a webserver for OpenCPN users. 
@bdbcat :  As an interim step could we have access to a new OpenCPN/manuals repo. I could certainly make html product using that repo, with suitable access rights. The product could be moved to www.opencpn.org by script or manually at first. 

I agree with Alec that this is not a good time for these discussions but Rick is forcing my hand.

@rgleason : For the second time please revert the dokuwiki so that it does not point at rasbats.github.io.

**Comment by rgleason** [comment]
Your request is new to me. What is the problem?  Where does github say that we can't use these as a public webserver? I was unaware of that.

We can't have people editing in two places. It is disastrous.

**Comment by rgleason** [comment]
Mike, 
Can you send me links to all the plugin docs?  (not the github.io)
I will add that to the Wiki, so they know where edits are to be made, 
Then if they want to see a facsimile of the html they will have to use github.io or the Wiki Plugins

**Comment by Rasbats** [comment]
>Your request is new to me. What is the problem? 

Email: Re: OpenCPN User Manual - Wiki Page "Plugins" changed
I don't want rasbats.github.io to be used for production purposes.

>Can you send me links to all the plugin docs? (not the github.io)
You have the links in the repo which was referred to in the same email.
[https://github.com/Rasbats/ocpn-manuals/](https://github.com/Rasbats/ocpn-manuals/)

**Comment by Rasbats** [comment]
[https://docs.github.com/en/pages/getting-started-with-github-pages/about-github-pages](https://docs.github.com/en/pages/getting-started-with-github-pages/about-github-pages)

**Comment by rgleason** [comment]
I see service limits on quantity but other than that I think it is ok. Maybe they claim some content rights that are a problem? I don't know.  Anyway I've taken the link off.

https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:opencpn_user_manual:plugins

This now leaves Opencpn Plugins in somewhat of a twilight zone.  The Wiki Plugin Documentation is Frozen and there are no active documentation pages. 

Can you advise how long this is going to be the situation?   Are we talking 1 month, 2 months, 3 months, 4 months, or more?
