### ISSUE TITLE
Missing image: p_release.png

### ISSUE THREAD

**Issue by leamas** [rgleason/ocpn-dev-manual#8]
fork_build_windows.adoc has a reference to  p_release.png. However, this  file is nowhere to find.

@rgleason: Can you look into this?

**Comment by rgleason** [comment]
Used Media Manager to search and it was not found

**Comment by leamas** [comment]
Can copy it to modules/ROOT/images?

**Comment by rgleason** [comment]
Alec, it does not appear to exist!

**Comment by rgleason** [comment]
Where is that located in the text,  page and I can try to search that.

**Comment by leamas** [comment]
Sorry, I misread, thought you found it.

So we have a reference to a non-existing image in *modules/ROOT/pages/fork_build_windows.adoc*. Shall we just drop it, or?

**Comment by rgleason** [comment]
Yes drop it. Please

**Comment by leamas** [comment]
Fixed in ae2d98e. Closing.
