### ISSUE TITLE
Fix the UI

### ISSUE THREAD

**Issue by leamas** [rgleason/ocpn-dev-manual#9]
The ui contaisn generic stuff like Services, Resources, Download etc. We need to customize this. Some discussion (great help) in https://antora.zulipchat.com/#narrow/stream/282400-users/topic/customizing.20the.20navbar.20links.20in.20the.20default.20UI

**Comment by rgleason** [comment]
I've logged in and downloaded it. Now it wants to connect to an organization.  Its a lot of diskk space.

**Comment by leamas** [comment]
Yoiu should not need to download anything. It's just a chat log.

**Comment by rgleason** [comment]
Ok
I willl remove the software

**Comment by leamas** [comment]
This is about adapting the UI for our needs, a task will have to cope with at some point. Reopening

**Comment by rgleason** [comment]
Which UI are we talking about here?

**Comment by leamas** [comment]
Everything around the asciidoc pages: black pane at top, including drop-down menus etc. left navigation pane, the TOC right pane and the useless bottom grey pane. All of this comes from the ui bundle, which we at one point needs to customize.

**Comment by leamas** [comment]
Nope, we are nowhere close to resolve this. It will require diving into npm and other tools to rebuild the UI bundle, after which we can start the process to customize it. This will take long time, it's a major task.

**Comment by leamas** [comment]
Fixed in https://github.com/leamas/ocpn-manuals/commit/2a32ca5b28f55b i. e.,in the ocpn-manuals project. Didn't realize that it belonged there when I filed this. Closing
